# -*- coding: utf-8 -*-
"""Q1_Total Least Squares and RANSAC.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zIHMmLGj-Dq4yJhZf9yWcjEHnakcOVSl
"""

import numpy as np
import matplotlib.pyplot as plt

#Total Least Squares Line Fitting
#line form: ax + by = d
def fit_tls_line(x, y):
    points = np.column_stack((x, y))
    centroid = points.mean(axis=0)

    centered = points - centroid
    S = centered.T @ centered

    eigvals, eigvecs = np.linalg.eigh(S)
    normal = eigvecs[:, np.argmin(eigvals)]

    a, b = normal
    d = a * centroid[0] + b * centroid[1]

    norm = np.sqrt(a**2 + b**2)
    return a / norm, b / norm, d / norm


def point_line_distance(x, y, line):
    a, b, d = line
    return np.abs(a * x + b * y - d)

#Load data
D = np.genfromtxt("/content/lines.csv", delimiter=",", skip_header=1)

X_cols = D[:, :3]   # x1, x2, x3
Y_cols = D[:, 3:]   # y1, y2, y3

#TLS for first line only
x1 = X_cols[:, 0]
y1 = Y_cols[:, 0]

line1_tls = fit_tls_line(x1, y1)
a, b, d = line1_tls

print("TLS Line Parameters:")
print(f"a = {a:.4f}")
print(f"b = {b:.4f}")
print(f"d = {d:.4f}")
print(f"Line equation: {a:.4f}x + {b:.4f}y = {d:.4f}")


#Plot
plt.figure(figsize=(6, 5))

plt.scatter(x1, y1, color="black", label="First line points")

x_range = np.linspace(x1.min() - 1, x1.max() + 1, 100)

if abs(b) > 1e-8:
    y_line = (d - a * x_range) / b
    plt.plot(x_range, y_line, color="red", linewidth=2, label="TLS fitted line")
else:
    x_line = d / a
    plt.axvline(x_line, color="red", linewidth=2, label="TLS fitted line")

plt.xlabel("x")
plt.ylabel("y")
plt.title("Total Least Squares Line Fitting")
plt.legend()
plt.grid(True)
plt.savefig("q1a_tls_line.png", dpi=300, bbox_inches="tight")
plt.show()

#RANSAC for three lines
def ransac_line(x, y, iterations=1000, threshold=0.25, min_inliers=2):
    best_line = None
    best_inliers = None
    best_count = 0

    n = len(x)

    for _ in range(iterations):
        ids = np.random.choice(n, 2, replace=False)

        x_sample = x[ids]
        y_sample = y[ids]

        line = fit_tls_line(x_sample, y_sample)
        dist = point_line_distance(x, y, line)

        inliers = dist < threshold
        count = np.sum(inliers)

        if count > best_count:
            best_count = count
            best_line = line
            best_inliers = inliers

    if best_count >= min_inliers:
        best_line = fit_tls_line(x[best_inliers], y[best_inliers])

    return best_line, best_inliers


X_all = X_cols.flatten()
Y_all = Y_cols.flatten()

remaining_x = X_all.copy()
remaining_y = Y_all.copy()

ransac_lines = []
ransac_inliers = []

for i in range(3):
    line, inliers = ransac_line(
        remaining_x,
        remaining_y,
        iterations=1000,
        threshold=0.25,
        min_inliers=2
    )

    ransac_lines.append(line)

    inlier_points = np.column_stack((remaining_x[inliers], remaining_y[inliers]))
    ransac_inliers.append(inlier_points)

    print(f"\nRANSAC Line {i+1}:")
    print(f"a = {line[0]:.4f}")
    print(f"b = {line[1]:.4f}")
    print(f"d = {line[2]:.4f}")
    print(f"Line equation: {line[0]:.4f}x + {line[1]:.4f}y = {line[2]:.4f}")
    print(f"Inliers found: {np.sum(inliers)}")

    # Remove the detected line points before finding the next line
    remaining_x = remaining_x[~inliers]
    remaining_y = remaining_y[~inliers]


#Plot
plt.figure(figsize=(7, 6))

plt.scatter(X_all, Y_all, s=18, color="lightgray", label="All points")

colors = ["red", "blue", "green"]
x_range = np.linspace(X_all.min() - 1, X_all.max() + 1, 200)

for i, line in enumerate(ransac_lines):
    a, b, d = line

    pts = ransac_inliers[i]

    plt.scatter(
        pts[:, 0],
        pts[:, 1],
        s=30,
        color=colors[i],
        label=f"Inliers Line {i+1}"
    )

    if abs(b) > 1e-8:
        y_line = (d - a * x_range) / b
        plt.plot(
            x_range,
            y_line,
            color=colors[i],
            linewidth=2,
            label=f"RANSAC Line {i+1}"
        )
    else:
        x_line = d / a
        plt.axvline(
            x_line,
            color=colors[i],
            linewidth=2,
            label=f"RANSAC Line {i+1}"
        )

plt.xlabel("x")
plt.ylabel("y")
plt.title("RANSAC Fitting of Three Lines")
plt.legend(fontsize=8)
plt.grid(True)
plt.savefig("q1b_ransac_three_lines.png", dpi=300, bbox_inches="tight")
plt.show()