# -*- coding: utf-8 -*-
"""Q3_circuit board_homography_transformation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ihidovJXRKIOHemCa453NhnF_rLEGug7
"""

import cv2 as cv
import numpy as np
import matplotlib.pyplot as plt
import os

os.makedirs("q3_outputs", exist_ok=True)

#Load images
img1 = cv.imread("/content/c1.jpg")
img2 = cv.imread("/content/c2.jpg")

if img1 is None or img2 is None:
    raise FileNotFoundError("Check image paths")

img1_rgb = cv.cvtColor(img1, cv.COLOR_BGR2RGB)
img2_rgb = cv.cvtColor(img2, cv.COLOR_BGR2RGB)

#Hardcoded corresponding points (MANUAL REPLACEMENT)

#Chosen matching points (same physical locations)
pts1 = np.array([
    [200, 150],   # top-left
    [500, 120],   # top-right
    [180, 600],   # bottom-left
    [520, 650],   # bottom-right
    [350, 400],   # center chip
    [480, 200]    # USB area
], dtype=np.float32)

pts2 = np.array([
    [220, 180],
    [540, 160],
    [200, 630],
    [560, 680],
    [380, 420],
    [520, 240]
], dtype=np.float32)

#Homography
H_manual, _ = cv.findHomography(pts1, pts2)

h2, w2 = img2.shape[:2]
warped_manual = cv.warpPerspective(img1, H_manual, (w2, h2))
warped_manual_rgb = cv.cvtColor(warped_manual, cv.COLOR_BGR2RGB)

#Show warped
plt.imshow(warped_manual_rgb)
plt.title("Warped Image (Manual Points)")
plt.axis("off")
plt.show()

#Difference Image
diff_manual = cv.absdiff(img2, warped_manual)
diff_manual_gray = cv.cvtColor(diff_manual, cv.COLOR_BGR2GRAY)

plt.imshow(diff_manual_gray, cmap="gray")
plt.title("Difference Image (Manual)")
plt.axis("off")
plt.show()


#ORB Matching
gray1 = cv.cvtColor(img1, cv.COLOR_BGR2GRAY)
gray2 = cv.cvtColor(img2, cv.COLOR_BGR2GRAY)

orb = cv.ORB_create(2000)

kp1, des1 = orb.detectAndCompute(gray1, None)
kp2, des2 = orb.detectAndCompute(gray2, None)

bf = cv.BFMatcher(cv.NORM_HAMMING, crossCheck=True)
matches = bf.match(des1, des2)
matches = sorted(matches, key=lambda x: x.distance)

good_matches = matches[:80]

match_img = cv.drawMatches(
    img1, kp1,
    img2, kp2,
    good_matches, None,
    flags=cv.DrawMatchesFlags_NOT_DRAW_SINGLE_POINTS
)

plt.figure(figsize=(12,6))
plt.imshow(cv.cvtColor(match_img, cv.COLOR_BGR2RGB))
plt.title("ORB Matches")
plt.axis("off")
plt.show()


#Homography using ORB + RANSAC
src_pts = np.float32([kp1[m.queryIdx].pt for m in good_matches]).reshape(-1,1,2)
dst_pts = np.float32([kp2[m.trainIdx].pt for m in good_matches]).reshape(-1,1,2)

H_orb, _ = cv.findHomography(src_pts, dst_pts, cv.RANSAC, 5.0)

warped_orb = cv.warpPerspective(img1, H_orb, (w2, h2))
warped_orb_rgb = cv.cvtColor(warped_orb, cv.COLOR_BGR2RGB)

diff_orb = cv.absdiff(img2, warped_orb)
diff_orb_gray = cv.cvtColor(diff_orb, cv.COLOR_BGR2GRAY)

# Show ORB results
plt.figure(figsize=(10,4))

plt.subplot(1,2,1)
plt.imshow(warped_orb_rgb)
plt.title("Warped (ORB)")
plt.axis("off")

plt.subplot(1,2,2)
plt.imshow(diff_orb_gray, cmap="gray")
plt.title("Difference (ORB)")
plt.axis("off")

plt.show()


# ============================================================
# Final Comparison
# ============================================================

plt.figure(figsize=(12,8))

plt.subplot(2,3,1)
plt.imshow(img1_rgb)
plt.title("c1")
plt.axis("off")

plt.subplot(2,3,2)
plt.imshow(img2_rgb)
plt.title("c2")
plt.axis("off")

plt.subplot(2,3,3)
plt.imshow(warped_manual_rgb)
plt.title("Manual Warp")
plt.axis("off")

plt.subplot(2,3,4)
plt.imshow(diff_manual_gray, cmap="gray")
plt.title("Manual Diff")
plt.axis("off")

plt.subplot(2,3,5)
plt.imshow(warped_orb_rgb)
plt.title("ORB Warp")
plt.axis("off")

plt.subplot(2,3,6)
plt.imshow(diff_orb_gray, cmap="gray")
plt.title("ORB Diff")
plt.axis("off")

plt.tight_layout()
plt.show()