# -*- coding: utf-8 -*-
"""Q2_camera_based_measurement.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1J5KBVXZz21edx4oDXsxgHgmhlzb4hbFE
"""

import cv2 as cv
import numpy as np
import matplotlib.pyplot as plt

# Load image
img = cv.imread("/content/earrings.jpg")
img_rgb = cv.cvtColor(img, cv.COLOR_BGR2RGB)

# Convert to HSV to segment gold earrings
hsv = cv.cvtColor(img, cv.COLOR_BGR2HSV)

# Gold/yellow color range
lower_gold = np.array([15, 40, 40])
upper_gold = np.array([45, 255, 255])

mask = cv.inRange(hsv, lower_gold, upper_gold)

# Clean mask
kernel = np.ones((5, 5), np.uint8)
mask = cv.morphologyEx(mask, cv.MORPH_CLOSE, kernel)
mask = cv.morphologyEx(mask, cv.MORPH_OPEN, kernel)

# Find contours
contours, _ = cv.findContours(mask, cv.RETR_EXTERNAL, cv.CHAIN_APPROX_SIMPLE)

# Keep large contours only
contours = [c for c in contours if cv.contourArea(c) > 1000]

# Sort left to right
contours = sorted(contours, key=lambda c: cv.boundingRect(c)[0])

# Camera parameters
f = 8                    # focal length in mm
Z = 720                  # distance to object in mm
pixel_size = 2.2e-3      # 2.2 micrometers = 0.0022 mm

scale = (Z / f) * pixel_size   # real-world mm per pixel

print(f"Scale = {scale:.4f} mm/pixel")

output = img_rgb.copy()

for i, c in enumerate(contours):
    x, y, w, h = cv.boundingRect(c)

    width_mm = w * scale
    height_mm = h * scale

    print(f"Earring {i+1}:")
    print(f"  Width  = {w} px = {width_mm:.2f} mm")
    print(f"  Height = {h} px = {height_mm:.2f} mm")

    cv.rectangle(output, (x, y), (x+w, y+h), (255, 0, 0), 3)
    cv.putText(output, f"{width_mm:.1f} x {height_mm:.1f} mm",
               (x, y-10), cv.FONT_HERSHEY_SIMPLEX, 0.8, (255, 0, 0), 2)

plt.figure(figsize=(10, 6))
plt.imshow(output)
plt.title("Detected Earrings with Estimated Sizes")
plt.axis("off")
plt.show()

plt.figure(figsize=(6, 6))
plt.imshow(mask, cmap="gray")
plt.title("Segmentation Mask")
plt.axis("off")
plt.show()